[package]
name = "darkstore-api"
version = "0.1.0"
edition = "2021"
rust-version = "1.95"
publish = false

[dependencies]
anyhow = "1"
axum = "0.8"
launchdarkly-server-sdk = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
strip = true
