# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.1"

gem "launchdarkly-server-sdk", "~> 8.16"
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"
gem "sinatra", "~> 4.1"

group :development, :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.1"
  gem "rake", "~> 13.2"
end
